export default {
  "meh": "¯\\_(ツ)_/¯",
  "lenny": "( ͡° ͜ʖ ͡°)",
  "do it": "(☞ﾟヮﾟ)☞",
  "bear": "ʕ•ᴥ•ʔ",
  "rage flip": "(ノಠ益ಠ)ノ彡┻━┻",
  "table flip": "(╯°□°)╯︵ ┻━┻",
  "table flipping battle": "(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)",
  "boxing": "(=O*_*)=O Q(*_*Q)",
  "neva eva": "('''( >.< )''')",
  "disapprove": "ಠ_ಠ",
  "kawaii shrug": "╮(.❛ᴗ❛.)╭",
  "y u no": "ლ(ಠ益ಠლ)",
  "glomp": "(づ￣ ³￣)づ",
  ":3": "(・3・)",
  "arms up": "(ノ・∀・)ノ",
  "nom nom": "(ˆڡˆ)v",
  "dance party": "♪┏(・o･)┛♪┗ ( ･o･) ┓♪",
  "dunno": "¯\\(º_o)/¯",
  "T_T": "(╥﹏╥)",
};
