export default {
  "T_T": "(╥﹏╥)",
  "arms up": "(ノ・∀・)ノ",
  "bear": "ʕ•ᴥ•ʔ",
  "bear flip": "ʕノ•ᴥ•ʔノ ︵ ┻━┻",
  "bear hug": "ʕっ•ᴥ•ʔっ",
  "boxing": "(ง •̀_•́)ง ผ(•̀_•́ผ)",
  "creep": "ԅ(≖‿≖ԅ)",
  "dance": "ᕕ(⌐■_■)ᕗ ♪♬",
  "dance party": "♪┏(・o･)┛♪┗ ( ･o･) ┓♪",
  "dear god why": "щ (ﾟДﾟщ)",
  "disapprove": "ಠ_ಠ",
  "do it": "(☞ﾟヮﾟ)☞",
  "dunno": "¯\\(º_o)/¯",
  "excited": "(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧",
  "facepalm": "(－‸ლ)",
  "glomp": "(づ￣ ³￣)づ",
  "kawaii shrug": "╮(.❛ᴗ❛.)╭",
  "kiss": "( −̀₃−́ )",
  "kyahh": "(੭≧▽≦)੭",
  "meh": "¯\\_(ツ)_/¯",
  "meow": "ฅ^•ﻌ•^ฅ",
  "neva eva": "('''( >.< )''')",
  "nom nom": "(っ˘ڡ˘ς)",
  "overwhelmed": "ᕙ(⇀‸↼‶)ᕗ",
  "rage flip": "(ノಠ益ಠ)ノ彡┻━┻",
  "really": "눈_눈",
  "run away": "ε=ε=(っ*´□`)っ",
  "satisfied": "ଘ(੭*ˊᵕˋ)੭*",
  "shmug": "ಸ‿ಸ",
  "slap": "(* ' Д ' )ﾉｼ )° ﾛ °)",
  "table flip": "(╯°□°)╯︵ ┻━┻",
  "table flipping battle": "(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)",
  "thug life": "\n(•_•)\n( •_•)>⌐■-■\n(⌐■_■)",
  "toldya": "(꒡⌓꒡)☞",
  "y u no": "ლ(ಠ益ಠლ)",
  "yolo": "Yᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ",
};
